#!/bin/bash
SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SRC_DIR

./public/station/build/build

af update mytilus-edulis

git add -A
git commit -m "./publish script commit"
git checkout master
git merge develop
git push heroku master